name: Build and Release

on:
  push:
    branches:
      - main  # Triggers the workflow on push events to the main branch

jobs:
  build:
    runs-on: windows-latest  # Build on a Windows runner

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Use Python 3.x

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Build Executable
      run: pyinstaller --onefile --windowed position-calculator.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: position-calculator
        path: dist/position-calculator.exe

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/position-calculator.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
